apiVersion: apps/v1
kind: Deployment
metadata:
  name: gsapp
  labels:
    app: gsapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gsapp
  template:
    metadata:
      name: gsapp
      labels:
        app: gsapp
    spec:
      containers:
        - name: gsapp
          image: 18339795172/gsapp:v1
          ports:
            - containerPort: 12306
              protocol: TCP
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 256Mi
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: gsapp-svc
spec:
  selector:
    app: gsapp
  ports:
    - port: 12306
      targetPort: 12306
  type: NodePort